project_id = "dbkuianwxcnptegdxknv"

[functions.send-course-instructor-invitation]
verify_jwt = false

[functions.accept-course-instructor-invitation]
verify_jwt = false

[functions.generate-full-course]
verify_jwt = false

[functions.accept-corporate-admin-invitation]
verify_jwt = false

[functions.send-corporate-member-invitation]
verify_jwt = false
